# Generated by Django 4.0.2 on 2022-02-05 20:30

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.categoria')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.presentacion')),
            ],
        ),
    ]
