# Generated by Django 4.0.2 on 2022-02-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('sector_comercial', models.CharField(max_length=200)),
                ('num_documento', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono1', models.CharField(blank=True, max_length=200)),
                ('telefono2', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
