# Generated by Django 4.0.2 on 2022-02-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_inicial', models.IntegerField(default=0)),
                ('stock_actual', models.IntegerField(default=0)),
                ('fecha_venc', models.DateTimeField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('serie', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('serie', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('detalle_ing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.detalleingreso')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.salida')),
            ],
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.ingreso'),
        ),
    ]
