CREATE DATABASE IF NOT EXISTS company;
use  company;

CREATE Table employee(
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) DEFAULT NULL,
    salary INT(11) DEFAULT NULL,
    PRIMARY KEY(id)
);

INSERT INTO employee(name,salary) VALUES ('MIGUEL ESPINOZA',2000),('CESAR MAYTA',7000),('LUIS AREBA',5000);